DROP TABLE IF EXISTS slack_user;

CREATE TABLE slack_user (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(127) NOT NULL DEFAULT 'noname',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)